// Generated by auto imports
export {}
declare global {
  const $fetch: typeof import('../fetch.mjs').$fetch
  const CANVAS_SHAPES: typeof import('../../app/utils/canvasShapes').CANVAS_SHAPES
  const CircleIcon: typeof import('../../app/utils/canvasShapes').CircleIcon
  const CylinderIcon: typeof import('../../app/utils/canvasShapes').CylinderIcon
  const DEFAULT_CONFIG: typeof import('../../app/utils/pageCurlMath').DEFAULT_CONFIG
  const DiamondIcon: typeof import('../../app/utils/canvasShapes').DiamondIcon
  const HexagonIcon: typeof import('../../app/utils/canvasShapes').HexagonIcon
  const MAX_COMPOSITE_DEPTH: typeof import('../../app/composables/useCycleDetector').MAX_COMPOSITE_DEPTH
  const MAX_FILE_SIZE_BYTES: typeof import('../../app/utils/fileValidator').MAX_FILE_SIZE_BYTES
  const ParallelogramIcon: typeof import('../../app/utils/canvasShapes').ParallelogramIcon
  const READER_FONTS: typeof import('../../app/composables/useReaderTypography').READER_FONTS
  const RectIcon: typeof import('../../app/utils/canvasShapes').RectIcon
  const RoundedIcon: typeof import('../../app/utils/canvasShapes').RoundedIcon
  const StarIcon: typeof import('../../app/utils/canvasShapes').StarIcon
  const TrapezoidIcon: typeof import('../../app/utils/canvasShapes').TrapezoidIcon
  const TriangleIcon: typeof import('../../app/utils/canvasShapes').TriangleIcon
  const abortNavigation: typeof import('../../node_modules/nuxt/dist/app/composables/router').abortNavigation
  const acceptHMRUpdate: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').acceptHMRUpdate
  const addRouteMiddleware: typeof import('../../node_modules/nuxt/dist/app/composables/router').addRouteMiddleware
  const applyAnnotationHighlight: typeof import('../../app/utils/readerHighlight').applyAnnotationHighlight
  const applyMarkdownFormat: typeof import('../../app/utils/markdownFormat').applyMarkdownFormat
  const applyPageHighlights: typeof import('../../app/utils/readerHighlight').applyPageHighlights
  const applyTheme: typeof import('../../app/composables/useSettings').applyTheme
  const applyThemeToCanvas: typeof import('../../app/utils/pageRasterizer').applyThemeToCanvas
  const calculateBezierPath: typeof import('../../app/utils/canvasGeometry').calculateBezierPath
  const calculateMidPoint: typeof import('../../app/utils/canvasGeometry').calculateMidPoint
  const callOnce: typeof import('../../node_modules/nuxt/dist/app/composables/once').callOnce
  const cancelIdleCallback: typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback').cancelIdleCallback
  const clamp: typeof import('../../app/utils/pageCurlMath').clamp
  const clearError: typeof import('../../node_modules/nuxt/dist/app/composables/error').clearError
  const clearNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').clearNuxtData
  const clearNuxtState: typeof import('../../node_modules/nuxt/dist/app/composables/state').clearNuxtState
  const clearPageHighlights: typeof import('../../app/utils/readerHighlight').clearPageHighlights
  const computeCurlGeometry: typeof import('../../app/utils/pageCurlMath').computeCurlGeometry
  const computed: typeof import('vue').computed
  const createError: typeof import('../../node_modules/nuxt/dist/app/composables/error').createError
  const createUseAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').createUseAsyncData
  const createUseFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').createUseFetch
  const customRef: typeof import('vue').customRef
  const defineAppConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineLazyHydrationComponent: typeof import('../../node_modules/nuxt/dist/app/composables/lazy-hydration').defineLazyHydrationComponent
  const defineNuxtComponent: typeof import('../../node_modules/nuxt/dist/app/composables/component').defineNuxtComponent
  const defineNuxtLink: typeof import('../../node_modules/nuxt/dist/app/components/nuxt-link').defineNuxtLink
  const defineNuxtPlugin: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineNuxtPlugin
  const defineNuxtRouteMiddleware: typeof import('../../node_modules/nuxt/dist/app/composables/router').defineNuxtRouteMiddleware
  const definePageMeta: typeof import('../../node_modules/nuxt/dist/app/composables/pages').definePageMeta
  const definePayloadPlugin: typeof import('../../node_modules/nuxt/dist/app/nuxt').definePayloadPlugin
  const definePayloadReducer: typeof import('../../node_modules/nuxt/dist/app/composables/payload').definePayloadReducer
  const definePayloadReviver: typeof import('../../node_modules/nuxt/dist/app/composables/payload').definePayloadReviver
  const defineStore: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').defineStore
  const deleteCachedBook: typeof import('../../app/utils/bookCache').deleteCachedBook
  const detectFileTypeFromArrayBuffer: typeof import('../../app/utils/fileValidator').detectFileTypeFromArrayBuffer
  const detectFileTypeFromBytes: typeof import('../../app/utils/fileValidator').detectFileTypeFromBytes
  const distance: typeof import('../../app/utils/pageCurlMath').distance
  const drawPlainTextToCanvas: typeof import('../../app/utils/pageRasterizer').drawPlainTextToCanvas
  const easeInOutCubic: typeof import('../../app/utils/pageCurlMath').easeInOutCubic
  const effect: typeof import('vue').effect
  const effectScope: typeof import('vue').effectScope
  const escapeHtml: typeof import('../../app/utils/markdownFormat').escapeHtml
  const formatErrorMessage: typeof import('../../app/utils/logger').formatErrorMessage
  const generateDidacticCoverDataUri: typeof import('../../app/utils/cover').generateDidacticCoverDataUri
  const generateDidacticCoverSvg: typeof import('../../app/utils/cover').generateDidacticCoverSvg
  const getAnchorPoint: typeof import('../../app/utils/canvasGeometry').getAnchorPoint
  const getAnnotationPageNumber: typeof import('../../app/utils/readerHighlight').getAnnotationPageNumber
  const getApiBase: typeof import('../../app/utils/apiBase').getApiBase
  const getApiRoot: typeof import('../../app/utils/apiBase').getApiRoot
  const getAppManifest: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getAppManifest
  const getBookFormat: typeof import('../../app/utils/cover').getBookFormat
  const getCachedBook: typeof import('../../app/utils/bookCache').getCachedBook
  const getClosestAnchorSide: typeof import('../../app/utils/canvasGeometry').getClosestAnchorSide
  const getCoverUrl: typeof import('../../app/utils/cover').getCoverUrl
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getDiamondPoints: typeof import('../../app/utils/canvasShapes').getDiamondPoints
  const getEffectiveNavIndex: typeof import('../../app/composables/useBottomNavbar').getEffectiveNavIndex
  const getHexagonPoints: typeof import('../../app/utils/canvasShapes').getHexagonPoints
  const getNavIndexFromPath: typeof import('../../app/composables/useBottomNavbar').getNavIndexFromPath
  const getParallelogramPoints: typeof import('../../app/utils/canvasShapes').getParallelogramPoints
  const getResolvedApiBase: typeof import('../../app/utils/apiBase').getResolvedApiBase
  const getRouteRules: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const getShapeIcon: typeof import('../../app/utils/canvasShapes').getShapeIcon
  const getStarPoints: typeof import('../../app/utils/canvasShapes').getStarPoints
  const getStorageBaseUrl: typeof import('../../app/utils/apiBase').getStorageBaseUrl
  const getTrapezoidPoints: typeof import('../../app/utils/canvasShapes').getTrapezoidPoints
  const getTrianglePoints: typeof import('../../app/utils/canvasShapes').getTrianglePoints
  const getVectorForSide: typeof import('../../app/utils/canvasGeometry').getVectorForSide
  const getVisibleTextChunks: typeof import('../../app/utils/readerHighlight').getVisibleTextChunks
  const h: typeof import('vue').h
  const hasInjectionContext: typeof import('vue').hasInjectionContext
  const hexToRgba: typeof import('../../app/utils/readerHighlight').hexToRgba
  const inject: typeof import('vue').inject
  const injectHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').injectHead
  const interpolateCurlState: typeof import('../../app/utils/pageCurlMath').interpolateCurlState
  const isNuxtError: typeof import('../../node_modules/nuxt/dist/app/composables/error').isNuxtError
  const isPrerendered: typeof import('../../node_modules/nuxt/dist/app/composables/payload').isPrerendered
  const isProductionMode: typeof import('../../app/utils/logger').isProductionMode
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isVue2: typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi').isVue2
  const isVue3: typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi').isVue3
  const lerp: typeof import('../../app/utils/pageCurlMath').lerp
  const loadPayload: typeof import('../../node_modules/nuxt/dist/app/composables/payload').loadPayload
  const logError: typeof import('../../app/utils/logger').logError
  const logWarn: typeof import('../../app/utils/logger').logWarn
  const markRaw: typeof import('vue').markRaw
  const matchesSignature: typeof import('../../app/utils/fileValidator').matchesSignature
  const navigateTo: typeof import('../../node_modules/nuxt/dist/app/composables/router').navigateTo
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onNuxtReady: typeof import('../../node_modules/nuxt/dist/app/composables/ready').onNuxtReady
  const onPrehydrate: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').onPrehydrate
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const prefetchComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').prefetchComponents
  const preloadComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').preloadComponents
  const preloadPayload: typeof import('../../node_modules/nuxt/dist/app/composables/payload').preloadPayload
  const preloadRouteComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').preloadRouteComponents
  const prerenderRoutes: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').prerenderRoutes
  const provide: typeof import('vue').provide
  const proxyRefs: typeof import('vue').proxyRefs
  const purgeClientSession: typeof import('../../app/composables/useAuth').purgeClientSession
  const rasterizeElementToCanvas: typeof import('../../app/utils/pageRasterizer').rasterizeElementToCanvas
  const reactive: typeof import('vue').reactive
  const readFileHeader: typeof import('../../app/utils/fileValidator').readFileHeader
  const readerProfiler: typeof import('../../app/utils/readerProfiler').readerProfiler
  const readerThemeToThemeMode: typeof import('../../app/composables/useSettings').readerThemeToThemeMode
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const refreshCookie: typeof import('../../node_modules/nuxt/dist/app/composables/cookie').refreshCookie
  const refreshNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').refreshNuxtData
  const reloadNuxtApp: typeof import('../../node_modules/nuxt/dist/app/composables/chunk').reloadNuxtApp
  const renderInlineMarkdown: typeof import('../../app/utils/markdownFormat').renderInlineMarkdown
  const renderMarkdown: typeof import('../../app/utils/markdownFormat').renderMarkdown
  const renderPageCurl: typeof import('../../app/utils/pageCurlMath').renderPageCurl
  const requestIdleCallback: typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback').requestIdleCallback
  const resetAnnotationsMemory: typeof import('../../app/composables/useAnnotations').resetAnnotationsMemory
  const resetFlashcardsMemory: typeof import('../../app/composables/useFlashcards').resetFlashcardsMemory
  const resetGraphMemory: typeof import('../../app/composables/useGraph').resetGraphMemory
  const resetNotesMemory: typeof import('../../app/composables/useNotes').resetNotesMemory
  const resetSettingsForTesting: typeof import('../../app/composables/useSettings').resetSettingsForTesting
  const resetUserBooksMemory: typeof import('../../app/composables/useUserBooks').resetUserBooksMemory
  const resolveBookCover: typeof import('../../app/utils/cover').resolveBookCover
  const resolveComponent: typeof import('vue').resolveComponent
  const saveCachedBook: typeof import('../../app/utils/bookCache').saveCachedBook
  const setInterval: typeof import('../../node_modules/nuxt/dist/app/compat/interval').setInterval
  const setPageLayout: typeof import('../../node_modules/nuxt/dist/app/composables/router').setPageLayout
  const setResponseStatus: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showError: typeof import('../../node_modules/nuxt/dist/app/composables/error').showError
  const storeToRefs: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').storeToRefs
  const themeModeToReaderTheme: typeof import('../../app/composables/useSettings').themeModeToReaderTheme
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const tryUseNuxtApp: typeof import('../../node_modules/nuxt/dist/app/nuxt').tryUseNuxtApp
  const unref: typeof import('vue').unref
  const updateAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').updateAppConfig
  const useAdminBooks: typeof import('../../app/composables/useAdminBooks').useAdminBooks
  const useAnnotations: typeof import('../../app/composables/useAnnotations').useAnnotations
  const useAnnouncer: typeof import('../../node_modules/nuxt/dist/app/composables/announcer').useAnnouncer
  const useAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').useAppConfig
  const useAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useAsyncData
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('../../app/composables/useAuth').useAuth
  const useBottomNavbar: typeof import('../../app/composables/useBottomNavbar').useBottomNavbar
  const useCanvas: typeof import('../../app/composables/useCanvas').useCanvas
  const useCanvasInking: typeof import('../../app/composables/useCanvasInking').useCanvasInking
  const useCatalog: typeof import('../../app/composables/useCatalog').useCatalog
  const useCommandPalette: typeof import('../../app/composables/useCommandPalette').useCommandPalette
  const useConverter: typeof import('../../app/composables/useConverter').useConverter
  const useCookie: typeof import('../../node_modules/nuxt/dist/app/composables/cookie').useCookie
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCycleDetector: typeof import('../../app/composables/useCycleDetector').useCycleDetector
  const useDidacticBooklet: typeof import('../../app/composables/useDidacticBooklet').useDidacticBooklet
  const useDrawing: typeof import('../../app/composables/useDrawing').useDrawing
  const useError: typeof import('../../node_modules/nuxt/dist/app/composables/error').useError
  const useFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').useFetch
  const useFlashcards: typeof import('../../app/composables/useFlashcards').useFlashcards
  const useGoogleDriveSync: typeof import('../../app/composables/useGoogleDriveSync').useGoogleDriveSync
  const useGraph: typeof import('../../app/composables/useGraph').useGraph
  const useHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').useHead
  const useHeadSafe: typeof import('../../node_modules/nuxt/dist/app/composables/head').useHeadSafe
  const useHydration: typeof import('../../node_modules/nuxt/dist/app/composables/hydrate').useHydration
  const useId: typeof import('vue').useId
  const useLayout: typeof import('../../node_modules/nuxt/dist/app/composables/layout').useLayout
  const useLazyAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useLazyAsyncData
  const useLazyFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').useLazyFetch
  const useLink: typeof import('vue-router').useLink
  const useLoadingIndicator: typeof import('../../node_modules/nuxt/dist/app/composables/loading-indicator').useLoadingIndicator
  const useLocalBookUpload: typeof import('../../app/composables/useLocalBookUpload').useLocalBookUpload
  const useModel: typeof import('vue').useModel
  const useNotes: typeof import('../../app/composables/useNotes').useNotes
  const useNuxtApp: typeof import('../../node_modules/nuxt/dist/app/nuxt').useNuxtApp
  const useNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useNuxtData
  const useOAuth: typeof import('../../app/composables/useOAuth').useOAuth
  const usePinia: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').usePinia
  const usePreviewMode: typeof import('../../node_modules/nuxt/dist/app/composables/preview').usePreviewMode
  const useReaderStore: typeof import('../../app/stores/readerStore').useReaderStore
  const useReaderTypography: typeof import('../../app/composables/useReaderTypography').useReaderTypography
  const useReadingStreak: typeof import('../../app/composables/useReadingStreak').useReadingStreak
  const useRequestEvent: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestEvent
  const useRequestFetch: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestFetch
  const useRequestHeader: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestHeader
  const useRequestHeaders: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestHeaders
  const useRequestURL: typeof import('../../node_modules/nuxt/dist/app/composables/url').useRequestURL
  const useResponseHeader: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useResponseHeader
  const useRoute: typeof import('../../node_modules/nuxt/dist/app/composables/router').useRoute
  const useRouteAnnouncer: typeof import('../../node_modules/nuxt/dist/app/composables/route-announcer').useRouteAnnouncer
  const useRouter: typeof import('../../node_modules/nuxt/dist/app/composables/router').useRouter
  const useRuntimeConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
  const useRuntimeHook: typeof import('../../node_modules/nuxt/dist/app/composables/runtime-hook').useRuntimeHook
  const useScript: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScript
  const useScriptAhrefsAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptAhrefsAnalytics
  const useScriptBingUet: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptBingUet
  const useScriptCalendly: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCalendly
  const useScriptClarity: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptClarity
  const useScriptCloudflareWebAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCloudflareWebAnalytics
  const useScriptCrisp: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCrisp
  const useScriptDatabuddyAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptDatabuddyAnalytics
  const useScriptEventPage: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptEventPage
  const useScriptFathomAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptFathomAnalytics
  const useScriptGoogleAdsense: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleAdsense
  const useScriptGoogleAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleAnalytics
  const useScriptGoogleMaps: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleMaps
  const useScriptGoogleRecaptcha: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleRecaptcha
  const useScriptGoogleSignIn: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleSignIn
  const useScriptGoogleTagManager: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleTagManager
  const useScriptGravatar: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGravatar
  const useScriptHotjar: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptHotjar
  const useScriptIntercom: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptIntercom
  const useScriptLemonSqueezy: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptLemonSqueezy
  const useScriptLinkedInInsight: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptLinkedInInsight
  const useScriptMatomoAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMatomoAnalytics
  const useScriptMetaPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMetaPixel
  const useScriptMixpanelAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMixpanelAnalytics
  const useScriptNpm: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptNpm
  const useScriptPayPal: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPayPal
  const useScriptPlausibleAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPlausibleAnalytics
  const useScriptPostHog: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPostHog
  const useScriptRedditPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptRedditPixel
  const useScriptRybbitAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptRybbitAnalytics
  const useScriptSegment: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSegment
  const useScriptSnapchatPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSnapchatPixel
  const useScriptSpeedCurve: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSpeedCurve
  const useScriptStripe: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptStripe
  const useScriptTikTokPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTikTokPixel
  const useScriptTriggerConsent: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTriggerConsent
  const useScriptTriggerElement: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTriggerElement
  const useScriptUmamiAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptUmamiAnalytics
  const useScriptUsercentrics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptUsercentrics
  const useScriptVercelAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptVercelAnalytics
  const useScriptVimeoPlayer: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptVimeoPlayer
  const useScriptXPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptXPixel
  const useScriptYouTubePlayer: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptYouTubePlayer
  const useSeoMeta: typeof import('../../node_modules/nuxt/dist/app/composables/head').useSeoMeta
  const useServerHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerHead
  const useServerHeadSafe: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerHeadSafe
  const useServerSeoMeta: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerSeoMeta
  const useSettings: typeof import('../../app/composables/useSettings').useSettings
  const useSettingsModal: typeof import('../../app/composables/useSettingsModal').useSettingsModal
  const useShadowRoot: typeof import('vue').useShadowRoot
  const useSlots: typeof import('vue').useSlots
  const useState: typeof import('../../node_modules/nuxt/dist/app/composables/state').useState
  const useStreakCelebration: typeof import('../../app/composables/useStreakCelebration').useStreakCelebration
  const useSyncEngine: typeof import('../../app/composables/useSyncEngine').useSyncEngine
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTransitionState: typeof import('vue').useTransitionState
  const useUserBooks: typeof import('../../app/composables/useUserBooks').useUserBooks
  const useUserMetrics: typeof import('../../app/composables/useUserMetrics').useUserMetrics
  const validateBookFile: typeof import('../../app/utils/fileValidator').validateBookFile
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const withCtx: typeof import('vue').withCtx
  const withDirectives: typeof import('vue').withDirectives
  const withKeys: typeof import('vue').withKeys
  const withMemo: typeof import('vue').withMemo
  const withModifiers: typeof import('vue').withModifiers
  const withScopeId: typeof import('vue').withScopeId
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { PageMeta } from '../../node_modules/nuxt/dist/app/composables/pages'
  import('../../node_modules/nuxt/dist/app/composables/pages')
  // @ts-ignore
  export type { AnnotationTheme, AnnotationItem, CreateAnnotationPayload } from '../../app/composables/useAnnotations'
  import('../../app/composables/useAnnotations')
  // @ts-ignore
  export type { AuthUser, LoginResponse } from '../../app/composables/useAuth'
  import('../../app/composables/useAuth')
  // @ts-ignore
  export type { BoundingBox, StrokePoint, InkingStroke } from '../../app/composables/useCanvasInking'
  import('../../app/composables/useCanvasInking')
  // @ts-ignore
  export type { CatalogBook } from '../../app/composables/useCatalog'
  import('../../app/composables/useCatalog')
  // @ts-ignore
  export type { ConversionOptions, ConversionStatus, ConversionResult } from '../../app/composables/useConverter'
  import('../../app/composables/useConverter')
  // @ts-ignore
  export type { RenderContextItem } from '../../app/composables/useCycleDetector'
  import('../../app/composables/useCycleDetector')
  // @ts-ignore
  export type { DidacticChapterItem, DidacticBookletItem } from '../../app/composables/useDidacticBooklet'
  import('../../app/composables/useDidacticBooklet')
  // @ts-ignore
  export type { FlashcardItem, DailyDeckResponse } from '../../app/composables/useFlashcards'
  import('../../app/composables/useFlashcards')
  // @ts-ignore
  export type { GoogleDriveSyncResult } from '../../app/composables/useGoogleDriveSync'
  import('../../app/composables/useGoogleDriveSync')
  // @ts-ignore
  export type { UploadLocalBookOptions, UploadLocalBookResult } from '../../app/composables/useLocalBookUpload'
  import('../../app/composables/useLocalBookUpload')
  // @ts-ignore
  export type { OAuthResult } from '../../app/composables/useOAuth'
  import('../../app/composables/useOAuth')
  // @ts-ignore
  export type { TypographyFont } from '../../app/composables/useReaderTypography'
  import('../../app/composables/useReaderTypography')
  // @ts-ignore
  export type { StreakDay, TodayActivity } from '../../app/composables/useReadingStreak'
  import('../../app/composables/useReadingStreak')
  // @ts-ignore
  export type { ThemeMode, EpubFontFamilyId, DictionaryLanguage, SettingsState, UserSettingsResponse } from '../../app/composables/useSettings'
  import('../../app/composables/useSettings')
  // @ts-ignore
  export type { UserMetricsData } from '../../app/composables/useUserMetrics'
  import('../../app/composables/useUserMetrics')
  // @ts-ignore
  export type { CachedBookEntry } from '../../app/utils/bookCache'
  import('../../app/utils/bookCache')
  // @ts-ignore
  export type { ShapeDefinition } from '../../app/utils/canvasShapes'
  import('../../app/utils/canvasShapes')
  // @ts-ignore
  export type { DidacticCoverParams, BookFormat } from '../../app/utils/cover'
  import('../../app/utils/cover')
  // @ts-ignore
  export type { MarkdownFormatResult } from '../../app/utils/markdownFormat'
  import('../../app/utils/markdownFormat')
  // @ts-ignore
  export type { ReaderTheme, RasterizeOptions } from '../../app/utils/pageRasterizer'
  import('../../app/utils/pageRasterizer')
  // @ts-ignore
  export type { TextChunk } from '../../app/utils/readerHighlight'
  import('../../app/utils/readerHighlight')
  // @ts-ignore
  export type { ProfilerCategory, ProfileStep, ProfileReport } from '../../app/utils/readerProfiler'
  import('../../app/utils/readerProfiler')
  // @ts-ignore
  export type { ReaderColorTheme, ReaderWidthMode } from '../../app/stores/readerStore'
  import('../../app/stores/readerStore')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly $fetch: UnwrapRef<typeof import('../fetch.mjs')['$fetch']>
    readonly CANVAS_SHAPES: UnwrapRef<typeof import('../../app/utils/canvasShapes')['CANVAS_SHAPES']>
    readonly CircleIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['CircleIcon']>
    readonly CylinderIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['CylinderIcon']>
    readonly DEFAULT_CONFIG: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['DEFAULT_CONFIG']>
    readonly DiamondIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['DiamondIcon']>
    readonly HexagonIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['HexagonIcon']>
    readonly MAX_COMPOSITE_DEPTH: UnwrapRef<typeof import('../../app/composables/useCycleDetector')['MAX_COMPOSITE_DEPTH']>
    readonly MAX_FILE_SIZE_BYTES: UnwrapRef<typeof import('../../app/utils/fileValidator')['MAX_FILE_SIZE_BYTES']>
    readonly ParallelogramIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['ParallelogramIcon']>
    readonly READER_FONTS: UnwrapRef<typeof import('../../app/composables/useReaderTypography')['READER_FONTS']>
    readonly RectIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['RectIcon']>
    readonly RoundedIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['RoundedIcon']>
    readonly StarIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['StarIcon']>
    readonly TrapezoidIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['TrapezoidIcon']>
    readonly TriangleIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['TriangleIcon']>
    readonly abortNavigation: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['abortNavigation']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['acceptHMRUpdate']>
    readonly addRouteMiddleware: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['addRouteMiddleware']>
    readonly applyAnnotationHighlight: UnwrapRef<typeof import('../../app/utils/readerHighlight')['applyAnnotationHighlight']>
    readonly applyMarkdownFormat: UnwrapRef<typeof import('../../app/utils/markdownFormat')['applyMarkdownFormat']>
    readonly applyPageHighlights: UnwrapRef<typeof import('../../app/utils/readerHighlight')['applyPageHighlights']>
    readonly applyTheme: UnwrapRef<typeof import('../../app/composables/useSettings')['applyTheme']>
    readonly applyThemeToCanvas: UnwrapRef<typeof import('../../app/utils/pageRasterizer')['applyThemeToCanvas']>
    readonly calculateBezierPath: UnwrapRef<typeof import('../../app/utils/canvasGeometry')['calculateBezierPath']>
    readonly calculateMidPoint: UnwrapRef<typeof import('../../app/utils/canvasGeometry')['calculateMidPoint']>
    readonly callOnce: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/once')['callOnce']>
    readonly cancelIdleCallback: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback')['cancelIdleCallback']>
    readonly clamp: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['clamp']>
    readonly clearError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['clearError']>
    readonly clearNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['clearNuxtData']>
    readonly clearNuxtState: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/state')['clearNuxtState']>
    readonly clearPageHighlights: UnwrapRef<typeof import('../../app/utils/readerHighlight')['clearPageHighlights']>
    readonly computeCurlGeometry: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['computeCurlGeometry']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['createError']>
    readonly createUseAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['createUseAsyncData']>
    readonly createUseFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['createUseFetch']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLazyHydrationComponent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/lazy-hydration')['defineLazyHydrationComponent']>
    readonly defineNuxtComponent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/component')['defineNuxtComponent']>
    readonly defineNuxtLink: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/components/nuxt-link')['defineNuxtLink']>
    readonly defineNuxtPlugin: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['defineNuxtPlugin']>
    readonly defineNuxtRouteMiddleware: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['defineNuxtRouteMiddleware']>
    readonly definePageMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/pages')['definePageMeta']>
    readonly definePayloadPlugin: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['definePayloadPlugin']>
    readonly definePayloadReducer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['definePayloadReducer']>
    readonly definePayloadReviver: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['definePayloadReviver']>
    readonly defineStore: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['defineStore']>
    readonly deleteCachedBook: UnwrapRef<typeof import('../../app/utils/bookCache')['deleteCachedBook']>
    readonly detectFileTypeFromArrayBuffer: UnwrapRef<typeof import('../../app/utils/fileValidator')['detectFileTypeFromArrayBuffer']>
    readonly detectFileTypeFromBytes: UnwrapRef<typeof import('../../app/utils/fileValidator')['detectFileTypeFromBytes']>
    readonly distance: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['distance']>
    readonly drawPlainTextToCanvas: UnwrapRef<typeof import('../../app/utils/pageRasterizer')['drawPlainTextToCanvas']>
    readonly easeInOutCubic: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['easeInOutCubic']>
    readonly effect: UnwrapRef<typeof import('vue')['effect']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly escapeHtml: UnwrapRef<typeof import('../../app/utils/markdownFormat')['escapeHtml']>
    readonly formatErrorMessage: UnwrapRef<typeof import('../../app/utils/logger')['formatErrorMessage']>
    readonly generateDidacticCoverDataUri: UnwrapRef<typeof import('../../app/utils/cover')['generateDidacticCoverDataUri']>
    readonly generateDidacticCoverSvg: UnwrapRef<typeof import('../../app/utils/cover')['generateDidacticCoverSvg']>
    readonly getAnchorPoint: UnwrapRef<typeof import('../../app/utils/canvasGeometry')['getAnchorPoint']>
    readonly getAnnotationPageNumber: UnwrapRef<typeof import('../../app/utils/readerHighlight')['getAnnotationPageNumber']>
    readonly getApiBase: UnwrapRef<typeof import('../../app/utils/apiBase')['getApiBase']>
    readonly getApiRoot: UnwrapRef<typeof import('../../app/utils/apiBase')['getApiRoot']>
    readonly getAppManifest: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/manifest')['getAppManifest']>
    readonly getBookFormat: UnwrapRef<typeof import('../../app/utils/cover')['getBookFormat']>
    readonly getCachedBook: UnwrapRef<typeof import('../../app/utils/bookCache')['getCachedBook']>
    readonly getClosestAnchorSide: UnwrapRef<typeof import('../../app/utils/canvasGeometry')['getClosestAnchorSide']>
    readonly getCoverUrl: UnwrapRef<typeof import('../../app/utils/cover')['getCoverUrl']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getDiamondPoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getDiamondPoints']>
    readonly getEffectiveNavIndex: UnwrapRef<typeof import('../../app/composables/useBottomNavbar')['getEffectiveNavIndex']>
    readonly getHexagonPoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getHexagonPoints']>
    readonly getNavIndexFromPath: UnwrapRef<typeof import('../../app/composables/useBottomNavbar')['getNavIndexFromPath']>
    readonly getParallelogramPoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getParallelogramPoints']>
    readonly getResolvedApiBase: UnwrapRef<typeof import('../../app/utils/apiBase')['getResolvedApiBase']>
    readonly getRouteRules: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/manifest')['getRouteRules']>
    readonly getShapeIcon: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getShapeIcon']>
    readonly getStarPoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getStarPoints']>
    readonly getStorageBaseUrl: UnwrapRef<typeof import('../../app/utils/apiBase')['getStorageBaseUrl']>
    readonly getTrapezoidPoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getTrapezoidPoints']>
    readonly getTrianglePoints: UnwrapRef<typeof import('../../app/utils/canvasShapes')['getTrianglePoints']>
    readonly getVectorForSide: UnwrapRef<typeof import('../../app/utils/canvasGeometry')['getVectorForSide']>
    readonly getVisibleTextChunks: UnwrapRef<typeof import('../../app/utils/readerHighlight')['getVisibleTextChunks']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasInjectionContext: UnwrapRef<typeof import('vue')['hasInjectionContext']>
    readonly hexToRgba: UnwrapRef<typeof import('../../app/utils/readerHighlight')['hexToRgba']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['injectHead']>
    readonly interpolateCurlState: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['interpolateCurlState']>
    readonly isNuxtError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['isNuxtError']>
    readonly isPrerendered: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['isPrerendered']>
    readonly isProductionMode: UnwrapRef<typeof import('../../app/utils/logger')['isProductionMode']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isVue2: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi')['isVue2']>
    readonly isVue3: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi')['isVue3']>
    readonly lerp: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['lerp']>
    readonly loadPayload: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['loadPayload']>
    readonly logError: UnwrapRef<typeof import('../../app/utils/logger')['logError']>
    readonly logWarn: UnwrapRef<typeof import('../../app/utils/logger')['logWarn']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly matchesSignature: UnwrapRef<typeof import('../../app/utils/fileValidator')['matchesSignature']>
    readonly navigateTo: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['navigateTo']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNuxtReady: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ready')['onNuxtReady']>
    readonly onPrehydrate: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['onPrehydrate']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly prefetchComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['prefetchComponents']>
    readonly preloadComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['preloadComponents']>
    readonly preloadPayload: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['preloadPayload']>
    readonly preloadRouteComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['preloadRouteComponents']>
    readonly prerenderRoutes: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['prerenderRoutes']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly proxyRefs: UnwrapRef<typeof import('vue')['proxyRefs']>
    readonly purgeClientSession: UnwrapRef<typeof import('../../app/composables/useAuth')['purgeClientSession']>
    readonly rasterizeElementToCanvas: UnwrapRef<typeof import('../../app/utils/pageRasterizer')['rasterizeElementToCanvas']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readFileHeader: UnwrapRef<typeof import('../../app/utils/fileValidator')['readFileHeader']>
    readonly readerProfiler: UnwrapRef<typeof import('../../app/utils/readerProfiler')['readerProfiler']>
    readonly readerThemeToThemeMode: UnwrapRef<typeof import('../../app/composables/useSettings')['readerThemeToThemeMode']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshCookie: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/cookie')['refreshCookie']>
    readonly refreshNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['refreshNuxtData']>
    readonly reloadNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/chunk')['reloadNuxtApp']>
    readonly renderInlineMarkdown: UnwrapRef<typeof import('../../app/utils/markdownFormat')['renderInlineMarkdown']>
    readonly renderMarkdown: UnwrapRef<typeof import('../../app/utils/markdownFormat')['renderMarkdown']>
    readonly renderPageCurl: UnwrapRef<typeof import('../../app/utils/pageCurlMath')['renderPageCurl']>
    readonly requestIdleCallback: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback')['requestIdleCallback']>
    readonly resetAnnotationsMemory: UnwrapRef<typeof import('../../app/composables/useAnnotations')['resetAnnotationsMemory']>
    readonly resetFlashcardsMemory: UnwrapRef<typeof import('../../app/composables/useFlashcards')['resetFlashcardsMemory']>
    readonly resetGraphMemory: UnwrapRef<typeof import('../../app/composables/useGraph')['resetGraphMemory']>
    readonly resetNotesMemory: UnwrapRef<typeof import('../../app/composables/useNotes')['resetNotesMemory']>
    readonly resetSettingsForTesting: UnwrapRef<typeof import('../../app/composables/useSettings')['resetSettingsForTesting']>
    readonly resetUserBooksMemory: UnwrapRef<typeof import('../../app/composables/useUserBooks')['resetUserBooksMemory']>
    readonly resolveBookCover: UnwrapRef<typeof import('../../app/utils/cover')['resolveBookCover']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly saveCachedBook: UnwrapRef<typeof import('../../app/utils/bookCache')['saveCachedBook']>
    readonly setInterval: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/interval')['setInterval']>
    readonly setPageLayout: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['setPageLayout']>
    readonly setResponseStatus: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['setResponseStatus']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['showError']>
    readonly storeToRefs: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['storeToRefs']>
    readonly themeModeToReaderTheme: UnwrapRef<typeof import('../../app/composables/useSettings')['themeModeToReaderTheme']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly tryUseNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['tryUseNuxtApp']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/config')['updateAppConfig']>
    readonly useAdminBooks: UnwrapRef<typeof import('../../app/composables/useAdminBooks')['useAdminBooks']>
    readonly useAnnotations: UnwrapRef<typeof import('../../app/composables/useAnnotations')['useAnnotations']>
    readonly useAnnouncer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/announcer')['useAnnouncer']>
    readonly useAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/config')['useAppConfig']>
    readonly useAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useAsyncData']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuth: UnwrapRef<typeof import('../../app/composables/useAuth')['useAuth']>
    readonly useBottomNavbar: UnwrapRef<typeof import('../../app/composables/useBottomNavbar')['useBottomNavbar']>
    readonly useCanvas: UnwrapRef<typeof import('../../app/composables/useCanvas')['useCanvas']>
    readonly useCanvasInking: UnwrapRef<typeof import('../../app/composables/useCanvasInking')['useCanvasInking']>
    readonly useCatalog: UnwrapRef<typeof import('../../app/composables/useCatalog')['useCatalog']>
    readonly useCommandPalette: UnwrapRef<typeof import('../../app/composables/useCommandPalette')['useCommandPalette']>
    readonly useConverter: UnwrapRef<typeof import('../../app/composables/useConverter')['useConverter']>
    readonly useCookie: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/cookie')['useCookie']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCycleDetector: UnwrapRef<typeof import('../../app/composables/useCycleDetector')['useCycleDetector']>
    readonly useDidacticBooklet: UnwrapRef<typeof import('../../app/composables/useDidacticBooklet')['useDidacticBooklet']>
    readonly useDrawing: UnwrapRef<typeof import('../../app/composables/useDrawing')['useDrawing']>
    readonly useError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['useError']>
    readonly useFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['useFetch']>
    readonly useFlashcards: UnwrapRef<typeof import('../../app/composables/useFlashcards')['useFlashcards']>
    readonly useGoogleDriveSync: UnwrapRef<typeof import('../../app/composables/useGoogleDriveSync')['useGoogleDriveSync']>
    readonly useGraph: UnwrapRef<typeof import('../../app/composables/useGraph')['useGraph']>
    readonly useHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useHead']>
    readonly useHeadSafe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useHeadSafe']>
    readonly useHydration: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/hydrate')['useHydration']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLayout: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/layout')['useLayout']>
    readonly useLazyAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useLazyAsyncData']>
    readonly useLazyFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['useLazyFetch']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLoadingIndicator: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/loading-indicator')['useLoadingIndicator']>
    readonly useLocalBookUpload: UnwrapRef<typeof import('../../app/composables/useLocalBookUpload')['useLocalBookUpload']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotes: UnwrapRef<typeof import('../../app/composables/useNotes')['useNotes']>
    readonly useNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['useNuxtApp']>
    readonly useNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useNuxtData']>
    readonly useOAuth: UnwrapRef<typeof import('../../app/composables/useOAuth')['useOAuth']>
    readonly usePinia: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['usePinia']>
    readonly usePreviewMode: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preview')['usePreviewMode']>
    readonly useReaderStore: UnwrapRef<typeof import('../../app/stores/readerStore')['useReaderStore']>
    readonly useReaderTypography: UnwrapRef<typeof import('../../app/composables/useReaderTypography')['useReaderTypography']>
    readonly useReadingStreak: UnwrapRef<typeof import('../../app/composables/useReadingStreak')['useReadingStreak']>
    readonly useRequestEvent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestEvent']>
    readonly useRequestFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestFetch']>
    readonly useRequestHeader: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestHeader']>
    readonly useRequestHeaders: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestHeaders']>
    readonly useRequestURL: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/url')['useRequestURL']>
    readonly useResponseHeader: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useResponseHeader']>
    readonly useRoute: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['useRoute']>
    readonly useRouteAnnouncer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/route-announcer')['useRouteAnnouncer']>
    readonly useRouter: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['useRuntimeConfig']>
    readonly useRuntimeHook: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/runtime-hook')['useRuntimeHook']>
    readonly useScript: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScript']>
    readonly useScriptAhrefsAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptAhrefsAnalytics']>
    readonly useScriptBingUet: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptBingUet']>
    readonly useScriptCalendly: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCalendly']>
    readonly useScriptClarity: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptClarity']>
    readonly useScriptCloudflareWebAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCloudflareWebAnalytics']>
    readonly useScriptCrisp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCrisp']>
    readonly useScriptDatabuddyAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptDatabuddyAnalytics']>
    readonly useScriptEventPage: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptEventPage']>
    readonly useScriptFathomAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptFathomAnalytics']>
    readonly useScriptGoogleAdsense: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleAdsense']>
    readonly useScriptGoogleAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleAnalytics']>
    readonly useScriptGoogleMaps: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleMaps']>
    readonly useScriptGoogleRecaptcha: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleRecaptcha']>
    readonly useScriptGoogleSignIn: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleSignIn']>
    readonly useScriptGoogleTagManager: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleTagManager']>
    readonly useScriptGravatar: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGravatar']>
    readonly useScriptHotjar: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptHotjar']>
    readonly useScriptIntercom: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptIntercom']>
    readonly useScriptLemonSqueezy: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptLemonSqueezy']>
    readonly useScriptLinkedInInsight: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptLinkedInInsight']>
    readonly useScriptMatomoAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMatomoAnalytics']>
    readonly useScriptMetaPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMetaPixel']>
    readonly useScriptMixpanelAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMixpanelAnalytics']>
    readonly useScriptNpm: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptNpm']>
    readonly useScriptPayPal: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPayPal']>
    readonly useScriptPlausibleAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPlausibleAnalytics']>
    readonly useScriptPostHog: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPostHog']>
    readonly useScriptRedditPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptRedditPixel']>
    readonly useScriptRybbitAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptRybbitAnalytics']>
    readonly useScriptSegment: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSegment']>
    readonly useScriptSnapchatPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSnapchatPixel']>
    readonly useScriptSpeedCurve: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSpeedCurve']>
    readonly useScriptStripe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptStripe']>
    readonly useScriptTikTokPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTikTokPixel']>
    readonly useScriptTriggerConsent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTriggerConsent']>
    readonly useScriptTriggerElement: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTriggerElement']>
    readonly useScriptUmamiAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptUmamiAnalytics']>
    readonly useScriptUsercentrics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptUsercentrics']>
    readonly useScriptVercelAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptVercelAnalytics']>
    readonly useScriptVimeoPlayer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptVimeoPlayer']>
    readonly useScriptXPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptXPixel']>
    readonly useScriptYouTubePlayer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptYouTubePlayer']>
    readonly useSeoMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useSeoMeta']>
    readonly useServerHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerHead']>
    readonly useServerHeadSafe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerHeadSafe']>
    readonly useServerSeoMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerSeoMeta']>
    readonly useSettings: UnwrapRef<typeof import('../../app/composables/useSettings')['useSettings']>
    readonly useSettingsModal: UnwrapRef<typeof import('../../app/composables/useSettingsModal')['useSettingsModal']>
    readonly useShadowRoot: UnwrapRef<typeof import('vue')['useShadowRoot']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useState: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/state')['useState']>
    readonly useStreakCelebration: UnwrapRef<typeof import('../../app/composables/useStreakCelebration')['useStreakCelebration']>
    readonly useSyncEngine: UnwrapRef<typeof import('../../app/composables/useSyncEngine')['useSyncEngine']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTransitionState: UnwrapRef<typeof import('vue')['useTransitionState']>
    readonly useUserBooks: UnwrapRef<typeof import('../../app/composables/useUserBooks')['useUserBooks']>
    readonly useUserMetrics: UnwrapRef<typeof import('../../app/composables/useUserMetrics')['useUserMetrics']>
    readonly validateBookFile: UnwrapRef<typeof import('../../app/utils/fileValidator')['validateBookFile']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly withCtx: UnwrapRef<typeof import('vue')['withCtx']>
    readonly withDirectives: UnwrapRef<typeof import('vue')['withDirectives']>
    readonly withKeys: UnwrapRef<typeof import('vue')['withKeys']>
    readonly withMemo: UnwrapRef<typeof import('vue')['withMemo']>
    readonly withModifiers: UnwrapRef<typeof import('vue')['withModifiers']>
    readonly withScopeId: UnwrapRef<typeof import('vue')['withScopeId']>
  }
}