// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/09/2026, 10:04:41
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
import cfg3 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/vichw/Aresta/apps/web/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/plugins/**/*.{js,ts,mjs}","C:/Users/vichw/Aresta/apps/web/app/composables/**/*.{js,ts,mjs}","C:/Users/vichw/Aresta/apps/web/app/utils/**/*.{js,ts,mjs}","C:/Users/vichw/Aresta/apps/web/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/vichw/Aresta/apps/web/app/app.config.{js,ts,mjs}","C:/Users/vichw/Aresta/apps/web/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;