// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/07/2026, 10:26:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/exati/projetos/Aresta/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/plugins/**/*.{js,ts,mjs}","/home/exati/projetos/Aresta/app/composables/**/*.{js,ts,mjs}","/home/exati/projetos/Aresta/app/utils/**/*.{js,ts,mjs}","/home/exati/projetos/Aresta/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/exati/projetos/Aresta/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;